version: "3"
services:
  xtodo:
    image: kmjayadeep/xtodo
    build: .
    environment:
      - MYSQL_DATABASE=xtodo
      - MYSQL_HOST=mysql
    ports:
      - 3000:3000
  mysql:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=xtodo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
